<?php

date_default_timezone_set('America/Lima');
error_reporting(E_ALL);


ini_set('include_path', ini_get('include_path').';E:/Proyectos/REPORTES/phpincludes/phpexcel/Classes/');
require_once 'E:/Proyectos/REPORTES/phpincludes/phpexcel/Classes/PHPExcel.php';/** PHPExcel_Writer_Excel2007 */
require_once 'E:/Proyectos/REPORTES/phpincludes/phpexcel/Classes/PHPExcel/Writer/Excel2007.php';
require_once 'E:/Proyectos/REPORTES/phpincludes/phpexcel/Classes/PHPExcel/IOFactory.php';

require_once 'E:/Proyectos/REPORTES/conexion/config.php';
require_once 'E:/Proyectos/REPORTES/conexion/MSSQLConnectionPDO.php';
require_once 'E:/Proyectos/REPORTES/factory/FactoryConnection.php';
require_once 'E:/Proyectos/REPORTES/includes/class.phpmailer.php';
require_once 'E:/Proyectos/REPORTES/includes/class.smtp.php';

$factoryConnection = FactoryConnection::create('mssql');
$connection = $factoryConnection->getConnection();


$columna=array("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","AA","AB","AC","AD","AE","AF","AG","AH","AI","AJ","AK","AL","AM","AN","AO","AP","AQ","AR","AS","AT","AU","AV","AW","AX","AY","AZ");

$font = array(
'font'  => array(
    'bold'  => true,
    'color' => array('rgb' => '000000'),
    'size'  => 8,
    'name'  => 'Verdana'
));
$title = array(
'font'  => array(
    'bold'  => true,
    'color' => array('rgb' => '000000'),
    'size'  => 13,
    'name'  => 'Verdana'
));
$font_cabe_blue = array(
'font'  => array(
    'bold'  => true,
    'color' => array('rgb' => '002060'),
    'size'  => 10,
    'name'  => 'Verdana'
));
$font_header = array(
'font'  => array(
    'bold'  => true,
    'color' => array('rgb' => '002060'),
    'size'  => 8,
    'name'  => 'Verdana'
));
$font_empresa_blue = array(
'font'  => array(
    'bold'  => true,
    'color' => array('rgb' => '1F4E78'),
    'size'  => 10,
    'name'  => 'Verdana'
));
$font_subtotal = array(
'font'  => array(
    'bold'  => true,
    'color' => array('rgb' => '000000'),
    'size'  => 10,
    'name'  => 'Verdana'
));
$border_mefium = array(
  'borders' => array(
      'allborders' => array(
          'style' => PHPExcel_Style_Border::BORDER_MEDIUM  
      )
));
$border_thin = array(
  'borders' => array(
      'allborders' => array(
          'style' => PHPExcel_Style_Border::BORDER_THIN  
      )
    )
);

$fondo_amarillo = array(
    'fill' => array(
        'type' => PHPExcel_Style_Fill::FILL_SOLID,
        'color' => array('rgb' => 'FFFF00')
    )
);

$fondo_celeste = array(
    'fill' => array(
        'type' => PHPExcel_Style_Fill::FILL_SOLID,
        'color' => array('rgb' => 'C1EFFF')
    )
);
$fondo_morado_claro = array(
    'fill' => array(
        'type' => PHPExcel_Style_Fill::FILL_SOLID,
        'color' => array('rgb' => 'D9E1F2')
    )
);
$fondo_claro = array(
    'fill' => array(
        'type' => PHPExcel_Style_Fill::FILL_SOLID,
        'color' => array('rgb' => 'F0F4FF')
    )
);
$fondo_celeste_claro = array(
    'fill' => array(
        'type' => PHPExcel_Style_Fill::FILL_SOLID,
        'color' => array('rgb' => 'DDEBF7')
    )
);

$fondo_rojo_claro = array(
    'fill' => array(
        'type' => PHPExcel_Style_Fill::FILL_SOLID,
        'color' => array('rgb' => 'FFE1E1')
    )
);

$fondo_verde_claro = array(
    'fill' => array(
        'type' => PHPExcel_Style_Fill::FILL_SOLID,
        'color' => array('rgb' => 'D4FDCF')
    )
);

$fecha_envio=date('Y-m-d H:i:s');
$codigo_cliente=$_GET['codigo_cliente'];

# DEFINIENDO AL VENDEDOR A MOTRAR (CAISAC,ANDEX,SEMILLAS) SE SEPUNE QUE TIENEN LA MISMA ASIGNACION VENDEDOR-CLIENTE




# CAPTURO TODOS LOS DOCUMENTOS OSEA SU ESTADO DE CUENTA DE CADA CLIENTE
$xls = new PHPExcel();
$xls->setActiveSheetIndex(0)->setTitle("ESTADO_CUENTA");
$xls->getActiveSheet()->mergeCells("C2:I2");
$xls->getActiveSheet()->SetCellValue("C2","DOCUMENTOS PENDIENTES POR CLIENTE");
$xls->getActiveSheet()->getStyle('C2')->applyFromArray($title);
$xls->getActiveSheet()->getStyle('C2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$xls->getActiveSheet()->SetCellValue("J2",$fecha_envio);
$xls->getActiveSheet()->mergeCells("J2:K2");
$xls->getActiveSheet()->getStyle('J2')->applyFromArray($font);
$xls->getActiveSheet()->getStyle('J2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

$defvend="	SELECT
			-- RTRIM(LTRIM(T.COD)) AS 'COD',
			RTRIM(LTRIM(T.CL_CCODCLI)) AS 'NUMERO_DOCUMENTO',
			RTRIM(LTRIM(T.CL_CNOMCLI)) AS 'RAZON_SOCIAL',
			RTRIM(LTRIM(CL_CVENDE)) AS 'CODVEND',
			RTRIM(LTRIM(VE_CNOMBRE)) AS 'VENDEDOR'
			FROM
			(
				-- SELECT '0001' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0001TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))
				-- UNION 
				SELECT '0002' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0002VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				UNION 
				SELECT '0003' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0003VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				UNION 
				SELECT '0004' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0004VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				-- UNION 
				-- SELECT '0005' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0005VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				-- UNION 
				-- SELECT '0006' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0006VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				-- UNION 
				-- SELECT '0007' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0007VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				-- UNION 
				-- SELECT '0008' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				-- UNION 
				-- SELECT '0009' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0009VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				-- UNION 
				-- SELECT '0015' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				UNION 
				SELECT '0016' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE,(SELECT RTRIM(LTRIM(VE_CNOMBRE)) FROM RSFACCAR..FT0016VEND WHERE VE_CCODIGO=CL_CVENDE) AS 'VE_CNOMBRE' FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
				-- UNION 
				-- SELECT '9999' AS 'COD',CL_CCODCLI,CL_CNOMCLI,CL_CVENDE FROM RSFACCAR..FT9999CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))) 
			) T
			WHERE
			T.CL_CCODCLI='$codigo_cliente' AND
			T.CL_CVENDE<>''
			GROUP BY RTRIM(LTRIM(T.CL_CCODCLI)),RTRIM(LTRIM(T.CL_CNOMCLI)) ,RTRIM(LTRIM(CL_CVENDE)),RTRIM(LTRIM(VE_CNOMBRE))
			";
$prdefvend = $connection->prepare($defvend);
$prdefvend->execute();
$ar_vend=$prdefvend->fetchAll(PDO::FETCH_ASSOC);

$contvend=4;
for($i=0;$i<=count($ar_vend)-1;$i++){

$xls->getActiveSheet()->SetCellValue("A4","CLIENTE: ".$ar_vend[$i]['RAZON_SOCIAL']);
$xls->getActiveSheet()->SetCellValue("A5","NRO DOCUMENTO: ".$ar_vend[$i]['NUMERO_DOCUMENTO']);
$xls->getActiveSheet()->getStyle('A4')->applyFromArray($font_cabe_blue);
$xls->getActiveSheet()->getStyle('A5')->applyFromArray($font_cabe_blue);


$xls->getActiveSheet()->SetCellValue("I".$contvend,"RESPONSABLE: ".$ar_vend[$i]['CODVEND']." - ".$ar_vend[$i]['VENDEDOR']);
$xls->getActiveSheet()->getStyle('I'.$contvend)->applyFromArray($font_cabe_blue);

$contvend++;
}

$fil=8;
$col=0;	

$xls->getActiveSheet()->getColumnDimensionByColumn(0)->setWidth(5);
$xls->getActiveSheet()->getColumnDimensionByColumn(1)->setWidth(15);
$xls->getActiveSheet()->getColumnDimensionByColumn(2)->setWidth(13);
$xls->getActiveSheet()->getColumnDimensionByColumn(3)->setWidth(13);
$xls->getActiveSheet()->getColumnDimensionByColumn(4)->setWidth(5);
$xls->getActiveSheet()->getColumnDimensionByColumn(5)->setWidth(10);
$xls->getActiveSheet()->getColumnDimensionByColumn(6)->setWidth(10);
$xls->getActiveSheet()->getColumnDimensionByColumn(7)->setWidth(16);
$xls->getActiveSheet()->getColumnDimensionByColumn(8)->setWidth(16);
$xls->getActiveSheet()->getColumnDimensionByColumn(9)->setWidth(13);
$xls->getActiveSheet()->getColumnDimensionByColumn(10)->setWidth(13);



$sqldocumentos = "		SELECT
						LTRIM(RTRIM(TM_CCIA)) AS 'CODIGO_EMPRESA',
						TM_CCODVEN AS 'CODVENDEDOR',
						VENDE AS 'VENDEDOR',
						LTRIM(RTRIM(TM_TIPDOC)) AS 'TD',
						LTRIM(RTRIM(TM_NRODOC)) AS 'DOCUMENTO',
						CONVERT(VARCHAR(10), TM_FECDOC, 103) AS 'FEC_EMISION',
						CONVERT(VARCHAR(10), TM_FECVEN, 103) AS 'FEC_VENCI',
						LTRIM(RTRIM(TM_TIPMON)) AS 'MONEDA',
						CASE LTRIM(RTRIM(TM_TIPMON)) 
						WHEN 'US' THEN TM_IMPTUS
						WHEN 'MN' THEN TM_IMPTMN
						ELSE 0 END AS 'IMPORTE',
						CASE LTRIM(RTRIM(TM_TIPMON)) 
						WHEN 'US' THEN TM_SALDUS
						WHEN 'MN' THEN TM_SALDMN
						ELSE 0 END AS 'SALDO',
						LTRIM(RTRIM(TM_LETSIT)) AS 'ESTADO',
						CASE LTRIM(RTRIM(TM_TIPDOC))
						WHEN 'LT' THEN 
							CASE LTRIM(RTRIM(TM_LETSIT))
							WHEN 'CO' THEN 'COBRANZA EN BANCO'
							WHEN 'CT' THEN ''
							WHEN 'COPR' THEN 'COBRANZA PROTESTADO'
							WHEN 'CTRE' THEN 'REBAJADO EN CARTERA'
							WHEN 'BC' THEN 'ENVIADO AL BANCO'
							WHEN 'CORE' THEN 'COBRANZA REBAJADA'
							WHEN 'COCA' THEN 'CANCELADO'
							ELSE '' END
						WHEN 'NC' THEN
							'SALDO A FAVOR'
						WHEN 'PA' THEN
							CASE SUBSTRING(REPLACE(LTRIM(RTRIM(TM_NRODOC)), ' ', ''), 1, 2)
								WHEN 'OP' THEN 'SALDO A FAVOR'
								WHEN 'DR' THEN 'AUTODETRACCIÓN'
								ELSE ''
							END
						ELSE '' END AS 'DET_ESTADO',
						LTRIM(RTRIM(TM_DESBAN)) AS 'BANCO',
						TM_NUMCOB AS 'NUM_COBRA'
						FROM
						(

							SELECT 
							'COMERCIAL ANDINA INDUSTRIAL SAC' AS TM_CCIADES,
							'0002' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,CD_DFECCAN AS TM_FECCAN, TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 

							ISNULL(LT_CSITUAC,'') AS TM_LETSIT, 
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO,
							1 AS 'NUM'
							From RSFACCAR..CC0002CART
							Left Join RSFACCAR..CC0002LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0002BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0002VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0002FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0002ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND 
							(CD_CESTADO<>'A')   AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X') 

							UNION 

							SELECT
							'GRUPO ANDEX' AS TM_CCIADES,
							'0003' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASE WHEN Datediff(DAY,CD_DFECDOC,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())<0 THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())>999 THEN 999 ELSE Datediff(DAY,CD_DFECDOC,Getdate()) END,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASE WHEN Datediff(DAY,CD_DFECVEN,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECVEN,Getdate())<0 THEN 0 WHEN Datediff(DAY,CD_DFECVEN,Getdate())>999 THEN 999 ELSE Datediff(DAY,CD_DFECVEN,Getdate()) END,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 

							ISNULL(LT_CSITUAC,'') AS TM_LETSIT, 
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO,
							2 AS 'NUM'
							FROM RSFACCAR..CC0003CART
							LEFT JOIN RSFACCAR..CC0003LETR ON CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0003BANC ON LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0003VEND ON CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0003FACC AS B ON CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0003ACUC AS C ON CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND
							(CD_CESTADO<>'A') AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION 

							SELECT
							'FERTILIZANTES Y SEMILLAS ANDINA' AS TM_CCIADES,
							'0004' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END, TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASE WHEN Datediff(DAY,CD_DFECDOC,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())<0 THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())>999 THEN 999 ELSE Datediff(DAY,CD_DFECDOC,Getdate()) END, 
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASE WHEN Datediff(DAY,CD_DFECVEN,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECVEN,Getdate())<0 THEN 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 

							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO ,
							3 AS 'NUM'
							FROM 
							RSFACCAR..CC0004CART
							LEFT JOIN RSFACCAR..CC0004LETR ON CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0004BANC ON LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0004VEND ON CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0004FACC AS B ON CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0004ACUC AS C ON CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE 
							CD_CCODCLI='$codigo_cliente' AND 
							(CD_CESTADO<>'A') AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION 

							SELECT 
							'CAISAC II' AS TM_CCIADES, 
							'0005' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 

							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO,
							5 AS 'NUM'
							FROM
							RSFACCAR..CC0005CART
							LEFT JOIN RSFACCAR..CC0005LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0005BANC On LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0005VEND On CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0005FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0005ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND 
							(CD_CESTADO<>'A')   AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION 

							SELECT 
							'ANDEX II' AS TM_CCIADES,
							'0006' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End, 
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 

							ISNULL(LT_CSITUAC,'') AS TM_LETSIT, 
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO ,
							6 AS 'NUM'
							From RSFACCAR..CC0006CART
							LEFT JOIN RSFACCAR..CC0006LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0006BANC On LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0006VEND On CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0006FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0006ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE 
							CD_CCODCLI='$codigo_cliente' AND 
							(CD_CESTADO<>'A') AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION 

							SELECT 
							'SEMILLAS II' AS TM_CCIADES, 
							'0007' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 

							ISNULL(LT_CSITUAC,'') AS TM_LETSIT, 
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN, 
							CD_CTDOREF AS TM_TIPDOCREF, 
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO ,
							7 AS 'NUM'
							From RSFACCAR..CC0007CART
							LEFT JOIN RSFACCAR..CC0007LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET    
							LEFT JOIN RSFACCAR..CC0007BANC On LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0007VEND On CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0007FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0007ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE 
							CD_CCODCLI='$codigo_cliente' AND 
							(CD_CESTADO<>'A') AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X') 

							/*UNION 

							SELECT 
							'REPRESENTACIONES SUNNY VALLEY S.A.C.' AS TM_CCIADES, 
							'0008' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,    
							CD_DFECDOC AS TM_FECDOC, 
							CD_CTDOREF AS TM_CTDREF, 
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT, 
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF, 
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO 
							From RSFACCAR..CC0008CART
							Left Join RSFACCAR..CC0008LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0008BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0008VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0008FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0008ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI    
							Where 
							CD_CCODCLI='$codigo_cliente' And
							(CD_CESTADO<>'A')   AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X') 
							*/
							UNION 

							SELECT 
							'GRUPO ANDINA SAC' AS TM_CCIADES, 
							'0009' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End, 
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN, 
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 

							ISNULL(LT_CSITUAC,'') AS TM_LETSIT, 
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN, 
							CD_CTDOREF AS TM_TIPDOCREF, 
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO ,
							8 AS 'NUM'
							From RSFACCAR..CC0009CART
							Left Join RSFACCAR..CC0009LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0009BANC On LT_CCODBAN=BC_CCODBAN    LEFT Join RSFACCAR..FT0009VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0009FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0009ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							Where CD_CCODCLI='$codigo_cliente' And 
							(CD_CESTADO<>'A')   AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							/*UNION 

							SELECT 
							'ICBA INGENIERIA DE CYCLONES SAC' AS TM_CCIADES, 
							'0015' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF, 
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END, 
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End, 
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN, 
							CD_CTDOREF AS TM_TIPDOCREF, 
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO 
							From RSFACCAR..CC0015CART   
							Left Join RSFACCAR..CC0015LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0015BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0015VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0015FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0015ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							Where 
							CD_CCODCLI='$codigo_cliente' And 
							(CD_CESTADO<>'A')   AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X') 
							*/
							UNION 

							SELECT
							'SUNNY VALLEY S.A.C.' AS TM_CCIADES,
							'0016' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End, 
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End, 
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,

							VENDE = CASE 
									WHEN VE_CTIPVEN='F' THEN CD_CCODVEN+'/'+VE_CCODLIN 
									ELSE	(
												SELECT A.VE_CNOMBRE FROM (RSFACCAR..FT0002VEND A LEFT OUTER JOIN RSFACCAR..FT0002LINE B  ON A.VE_CCODLIN = B.LI_CCODLIN)
												LEFT OUTER JOIN RSFACCAR..FT0002SUPV E ON A.VE_CCOSUPV = E.SU_CCODIGO  
												LEFT OUTER JOIN RSFACCAR..FT0002ZONV D ON A.VE_CZONVTA = D.ZV_CCODZON ,RSFACCAR..AL0002TABL C  
												WHERE A.VE_CTIPVEN = C.TG_CCLAVE  AND C.TG_CCOD='53' AND A.VE_CCODIGO=CD_CCODVEN
											)
									END, 
							
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT, 
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN, 
							CD_CTDOREF AS TM_TIPDOCREF, 
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO ,
							4 AS 'NUM'
							From RSFACCAR..CC0016CART
							Left Join RSFACCAR..CC0016LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0016BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0016VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0016FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0016ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE 
							CD_CCODCLI='$codigo_cliente' And 
							(CD_CESTADO<>'A')   AND 
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')
						) AS T
						WHERE
						T.TM_ESTADO='V'
						ORDER BY T.NUM,T.TM_FECVEN ASC

						";

$prdocumentos = $connection->prepare($sqldocumentos, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
$prdocumentos->execute();

$cod="";
$nroreg=0;

$caisacsoles=0;$caisacdolares=0;$cantcaisac=0; // 0002 COMERCIAL ANDINA INDUSTRIAL SAC
$andexsoles=0;$andexdolares=0;$cantandex=0; // 0003 GRUPO ANDEX
$semillassoles=0;$semillasdolares=0;$cantsemillas=0; // 0004 FERTILIZANTES Y SEMILLAS ANDINA
$caisac2soles=0;$caisac2dolares=0;$cantcaisac2=0; // 0005 CAISAC II
$andex2soles=0;$andex2dolares=0;$cantandex2=0; // 0006 ANDEX II
$semillas2soles=0;$semillas2dolares=0;$cantsemillas2=0; // 0007 SEMILLAS II
$gasoles=0;$gadolares=0;$cantga=0; // 0009 GRUPO ANDINA SAC
$sunnysoles=0;$sunnydolares=0;$cantsunny=0; // 0016 SUNNY VALLEY S.A.C.

$totaldolares=0;
$totalsoles=0;
$cantreg=$prdocumentos->rowCount();
// $cantreg=count($prdocumentos->fetchAll(PDO::FETCH_ASSOC));
// echo $cantreg;

while($datos_muestra=$prdocumentos->fetch(PDO::FETCH_ASSOC)) {
	$fil++;
	$nroreg++;
	if($datos_muestra['CODIGO_EMPRESA']=='0002'){
		$cantcaisac++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$caisacdolares=$caisacdolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$caisacsoles=$caisacsoles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}		

	}
	if($datos_muestra['CODIGO_EMPRESA']=='0003'){
		$cantandex++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$andexdolares=$andexdolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$andexsoles=$andexsoles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}
	}
	if($datos_muestra['CODIGO_EMPRESA']=='0004'){
		$cantsemillas++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$semillasdolares=$semillasdolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$semillassoles=$semillassoles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}
	}
	if($datos_muestra['CODIGO_EMPRESA']=='0005'){
		$cantcaisac2++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$caisac2dolares=$caisac2dolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$caisac2soles=$caisac2soles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}
	}
	if($datos_muestra['CODIGO_EMPRESA']=='0006'){
		$cantandex2++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$andex2dolares=$andex2dolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$andex2soles=$andex2soles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}
	}
	if($datos_muestra['CODIGO_EMPRESA']=='0007'){
		$cantsemillas2++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$semillas2dolares=$semillas2dolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$semillas2soles=$semillas2soles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}
	}
	if($datos_muestra['CODIGO_EMPRESA']=='0009'){
		$cantga++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$gadolares=$gadolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$gasoles=$gasoles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}
	}	
	if($datos_muestra['CODIGO_EMPRESA']=='0016'){
		$cantsunny++;
		if($datos_muestra["TD"]=='FT' || $datos_muestra["TD"]=='BV' || $datos_muestra["TD"]=='ND' || $datos_muestra["TD"]=='LT' || $datos_muestra["TD"]=='TK'){
			if($datos_muestra["MONEDA"]=='US'){
				$sunnydolares=$sunnydolares+$datos_muestra["SALDO"];
				$totaldolares=$totaldolares+$datos_muestra["SALDO"];
			}else if($datos_muestra["MONEDA"]=='MN'){
				$sunnysoles=$sunnysoles+$datos_muestra["SALDO"];
				$totalsoles=$totalsoles+$datos_muestra["SALDO"];
			}
		}
	}
	if($cod!=$datos_muestra['CODIGO_EMPRESA']){
		if($fil==9){
			$fil=$fil+1;
			$emp=$datos_muestra['CODIGO_EMPRESA'];
			$sqlempresa=" SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
			$prempresa = $connection->prepare($sqlempresa);
			$prempresa->execute();					
			$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);					
			$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil-1), $empresa[0]['NOMBRE']);
			$xls->getActiveSheet()->getStyle($columna[$col+0].($fil-1))->applyFromArray($font_empresa_blue);
			$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
			$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
			$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
			$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
			$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
			$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
			$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
			$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
			$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
			$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
			$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
			$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
			$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
			$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
			$fil=$fil+1;
		}else{
			if($cod=='0002'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $caisacdolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $caisacsoles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE ANDEX*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa=" SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}else if($cod=='0003'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $andexdolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $andexsoles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE SEMILLAS*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa="SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;				
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}else if($cod=='0004'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillasdolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillassoles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE SEMILLAS*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa="SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;				
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}else if($cod=='0005'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $caisac2dolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $caisac2soles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE SEMILLAS*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa="SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;				
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}else if($cod=='0006'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $andex2dolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $andex2soles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE SEMILLAS*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa="SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;				
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}else if($cod=='0007'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillas2dolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillas2soles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE SEMILLAS*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa="SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;				
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}else if($cod=='0009'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $gadolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $gasoles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE SEMILLAS*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa="SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;				
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}else if($cod=='0016'){
				$fil=$fil+1;
				$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
				$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
				$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $sunnydolares);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				$fil=$fil+1;
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $sunnysoles);
				$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
				/*NOMBRE DE SEMILLAS*/
				$fil=$fil+2;
				$emp=$datos_muestra['CODIGO_EMPRESA'];
				$sqlempresa="SELECT RTRIM(LTRIM(AC_CNOMCIA)) AS NOMBRE FROM RSFACCAR..ALCIAS WHERE RTRIM(LTRIM(AC_CCIA))='$emp'";
				$prempresa = $connection->prepare($sqlempresa);
				$prempresa->execute();					
				$empresa=$prempresa->fetchAll(PDO::FETCH_ASSOC);
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].($fil), $empresa[0]['NOMBRE']);	
				$xls->getActiveSheet()->getStyle($columna[$col+0].($fil))->applyFromArray($font_empresa_blue);
				$fil=$fil+1;				
				$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, "TD");
				$xls->getActiveSheet()->SetCellValue($columna[$col+1].$fil, "DOCUMENTO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, "FEC.EMISION");
				$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, "FEC.VENCI.");
				$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, "MO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, "IMPORTE");
				$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, "SALDO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, "ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, "DET.ESTADO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, "BANCO");
				$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil, "NUM.COBRA.");
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_morado_claro);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($font_header);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
				$fil=$fil+0;
			}
			$fil=$fil+1;
		}
	}

	$xls->getActiveSheet()->SetCellValue($columna[$col+0].$fil, $datos_muestra["TD"]);
	$xls->getActiveSheet()->setCellValueExplicit($columna[$col+1].$fil, $datos_muestra["DOCUMENTO"],PHPExcel_Cell_DataType::TYPE_STRING);
	$xls->getActiveSheet()->SetCellValue($columna[$col+2].$fil, $datos_muestra["FEC_EMISION"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+3].$fil, $datos_muestra["FEC_VENCI"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil, $datos_muestra["MONEDA"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+5].$fil, $datos_muestra["IMPORTE"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+6].$fil, $datos_muestra["SALDO"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+7].$fil, $datos_muestra["ESTADO"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+8].$fil, $datos_muestra["DET_ESTADO"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil,$datos_muestra["BANCO"]);
	$xls->getActiveSheet()->SetCellValue($columna[$col+10].$fil,$datos_muestra["NUM_COBRA"]);
	$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($fondo_claro);
	$xls->getActiveSheet()->getStyle('A'.$fil.':K'.$fil)->applyFromArray($border_thin);
	$xls->getActiveSheet()->getStyle($columna[$col+0].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	$xls->getActiveSheet()->getStyle($columna[$col+5].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
	$xls->getActiveSheet()->getStyle($columna[$col+6].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);

	$cod=$datos_muestra['CODIGO_EMPRESA'];

	if($nroreg==$cantreg){				
		if($cod=='0002'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $caisacdolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $caisacsoles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		if($cod=='0003'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $andexdolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $andexsoles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		if($cod=='0004'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillasdolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillassoles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		if($cod=='0005'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillasdolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillassoles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		if($cod=='0006'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillasdolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillassoles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		if($cod=='0007'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillas2dolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillas2soles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		if($cod=='0009'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillasdolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $semillassoles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		if($cod=='0016'){
			$fil=$fil+2;
			$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
			$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL POR EMPRESA");
			$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $sunnydolares);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
			$fil=$fil+1;
			$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
			$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);				
			$xls->getActiveSheet()->getStyle($columna[$col+9])->applyFromArray($font_subtotal);
			$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $sunnysoles);
			$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		}
		$fil=$fil+3;
		$xls->getActiveSheet()->mergeCells("A".$fil.":C".$fil);
		$xls->getActiveSheet()->getStyle('A'.$fil)->applyFromArray($font_subtotal);
		$xls->getActiveSheet()->SetCellValue('A'.$fil,"TOTAL GENERAL");
		$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);				
		$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'US');
		$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
		$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($border_mefium);
		$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);	
		$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $totaldolares);
		$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
		$fil=$fil+1;
		$xls->getActiveSheet()->getStyle($columna[$col+4])->applyFromArray($font_subtotal);
		$xls->getActiveSheet()->SetCellValue($columna[$col+4].$fil,'MN');
		$xls->getActiveSheet()->getStyle($columna[$col+4].$fil)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
		$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($border_mefium);
		$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->applyFromArray($font_subtotal);
		$xls->getActiveSheet()->SetCellValue($columna[$col+9].$fil, $totalsoles);
		$xls->getActiveSheet()->getStyle($columna[$col+9].$fil)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
	}

}

$date = new DateTime($fecha_envio);

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="Estado de Cuenta '.$codigo_cliente.' --- '.$date->format('Y-m-d H.i.s').'.xlsx"');
header('Cache-Control: max-age=0');
$objWriter = PHPExcel_IOFactory::createWriter($xls, 'Excel2007');
$objWriter->save('php://output');
exit();

?>