<?php

class MSSQLCuentaDAO {

	public function searchbycodigo_cliente($codigo_cliente) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql_Exist_cli = "	SELECT
							T.CL_CCODCLI,
							T.CL_CNOMCLI
							FROM
							(
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0001TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))
								-- UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								-- UNION
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								-- UNION
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								-- UNION
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT9999CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
							)  T
							WHERE
							T.CL_CCODCLI='$codigo_cliente'";
		$pr = $connection->prepare($sql_Exist_cli);
		if ($pr->execute()) {
			$arr_cli = $pr->fetchAll(PDO::FETCH_ASSOC);
			if (count($arr_cli) > 0) {
				echo json_encode(array("rst" => true, "msg" => "Cliente existe", "ardata" => $arr_cli));
			} else {
				echo json_encode(array("rst" => false, "msg" => "Cliente no exite", "ardata" => $arr_cli));
			}
		}
	}

	public function searchbyrazon_social($rz) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql_Exist_cli = "	SELECT
							T.CL_CCODCLI,
							T.CL_CNOMCLI
							FROM
							(
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0001TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))
								-- UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								-- UNION
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								-- UNION
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								UNION
								SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  -- WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
								-- UNION
								-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT9999CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
							)  T
							WHERE
							T.CL_CNOMCLI LIKE '%$rz%'";
		$pr = $connection->prepare($sql_Exist_cli);
		if ($pr->execute()) {
			$arr_cli = $pr->fetchAll(PDO::FETCH_ASSOC);
			if (count($arr_cli) > 0) {
				echo json_encode(array("rst" => true, "msg" => "Cliente existe", "ardata" => $arr_cli));
			} else {
				echo json_encode(array("rst" => false, "msg" => "Cliente no exite", "ardata" => $arr_cli));
			}
		}
	}

	public function ifexist_deuda_cliente($codigo_cliente) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql_Exist_deuda = "	SELECT
						TM_CCIA AS 'CODIGO_EMPRESA',
						LTRIM(RTRIM(TM_TIPDOC)) AS 'TD',
						LTRIM(RTRIM(TM_NRODOC)) AS 'DOCUMENTO',
						CONVERT(VARCHAR(10), TM_FECDOC, 103) AS 'FEC_EMISION',
						CONVERT(VARCHAR(10), TM_FECVEN, 103) AS 'FEC_VENCI',
						LTRIM(RTRIM(TM_TIPMON)) AS 'MONEDA',
						CASE LTRIM(RTRIM(TM_TIPMON))
						WHEN 'US' THEN TM_IMPTUS
						WHEN 'MN' THEN TM_IMPTMN
						ELSE 0 END AS 'IMPORTE',
						CASE LTRIM(RTRIM(TM_TIPMON))
						WHEN 'US' THEN TM_SALDUS
						WHEN 'MN' THEN TM_SALDMN
						ELSE 0 END AS 'SALDO',
						LTRIM(RTRIM(TM_LETSIT)) AS 'ESTADO',
						CASE LTRIM(RTRIM(TM_LETSIT))
						WHEN 'CO' THEN 'COBRANZA EN BANCO'
						WHEN 'CT' THEN ''
						WHEN 'COPR' THEN 'COBRANZA PROTESTADO'
						WHEN 'CTRE' THEN 'REBAJADO EN CARTERA'
						WHEN 'BC' THEN 'ENVIADO AL BANCO'
						WHEN 'CORE' THEN 'COBRANZA REBAJADA'
						WHEN 'COCA' THEN 'CANCELADO'
						ELSE ''  END AS 'DET_ESTADO',
						LTRIM(RTRIM(TM_DESBAN)) AS 'BANCO',
						TM_NUMCOB AS 'NUM_COBRA'
						FROM
						(

							SELECT
							'COMERCIAL ANDINA INDUSTRIAL SAC' AS TM_CCIADES,
							'0002' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,CD_DFECCAN AS TM_FECCAN, TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0002CART
							Left Join RSFACCAR..CC0002LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0002BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0002VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0002FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0002ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND
							(CD_CESTADO<>'A')   AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION

							SELECT
							'GRUPO ANDEX' AS TM_CCIADES,
							'0003' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASE WHEN Datediff(DAY,CD_DFECDOC,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())<0 THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())>999 THEN 999 ELSE Datediff(DAY,CD_DFECDOC,Getdate()) END,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASE WHEN Datediff(DAY,CD_DFECVEN,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECVEN,Getdate())<0 THEN 0 WHEN Datediff(DAY,CD_DFECVEN,Getdate())>999 THEN 999 ELSE Datediff(DAY,CD_DFECVEN,Getdate()) END,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							FROM RSFACCAR..CC0003CART
							LEFT JOIN RSFACCAR..CC0003LETR ON CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0003BANC ON LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0003VEND ON CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0003FACC AS B ON CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0003ACUC AS C ON CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND
							(CD_CESTADO<>'A') AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION

							SELECT
							'FERTILIZANTES Y SEMILLAS ANDINA' AS TM_CCIADES,
							'0004' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END, TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASE WHEN Datediff(DAY,CD_DFECDOC,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())<0 THEN 0 WHEN Datediff(DAY,CD_DFECDOC,Getdate())>999 THEN 999 ELSE Datediff(DAY,CD_DFECDOC,Getdate()) END,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASE WHEN Datediff(DAY,CD_DFECVEN,Getdate()) IS NULL THEN 0 WHEN Datediff(DAY,CD_DFECVEN,Getdate())<0 THEN 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							FROM
							RSFACCAR..CC0004CART
							LEFT JOIN RSFACCAR..CC0004LETR ON CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0004BANC ON LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0004VEND ON CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0004FACC AS B ON CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0004ACUC AS C ON CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND
							(CD_CESTADO<>'A') AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION

							SELECT
							'CAISAC II' AS TM_CCIADES,
							'0005' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							FROM
							RSFACCAR..CC0005CART
							LEFT JOIN RSFACCAR..CC0005LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0005BANC On LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0005VEND On CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0005FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0005ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND
							(CD_CESTADO<>'A')   AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION

							SELECT
							'ANDEX II' AS TM_CCIADES,
							'0006' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0006CART
							LEFT JOIN RSFACCAR..CC0006LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0006BANC On LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0006VEND On CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0006FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0006ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND
							(CD_CESTADO<>'A') AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION

							SELECT
							'SEMILLAS II' AS TM_CCIADES,
							'0007' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0007CART
							LEFT JOIN RSFACCAR..CC0007LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							LEFT JOIN RSFACCAR..CC0007BANC On LT_CCODBAN=BC_CCODBAN
							LEFT JOIN RSFACCAR..FT0007VEND On CD_CCODVEN=VE_CCODIGO
							LEFT JOIN RSFACCAR..FT0007FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT JOIN RSFACCAR..FT0007ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							WHERE
							CD_CCODCLI='$codigo_cliente' AND
							(CD_CESTADO<>'A') AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							/*UNION

							SELECT
							'REPRESENTACIONES SUNNY VALLEY S.A.C.' AS TM_CCIADES,
							'0008' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0008CART
							Left Join RSFACCAR..CC0008LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0008BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0008VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0008FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0008ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							Where
							CD_CCODCLI='$codigo_cliente' And
							(CD_CESTADO<>'A')   AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')
							*/
							UNION

							SELECT
							'GRUPO ANDINA SAC' AS TM_CCIADES,
							'0009' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0009CART
							Left Join RSFACCAR..CC0009LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0009BANC On LT_CCODBAN=BC_CCODBAN    LEFT Join RSFACCAR..FT0009VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0009FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0009ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							Where CD_CCODCLI='$codigo_cliente' And
							(CD_CESTADO<>'A')   AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							/*UNION

							SELECT
							'ICBA INGENIERIA DE CYCLONES SAC' AS TM_CCIADES,
							'0015' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0015CART
							Left Join RSFACCAR..CC0015LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0015BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0015VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0015FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0015ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							Where
							CD_CCODCLI='$codigo_cliente' And
							(CD_CESTADO<>'A')   AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')
							*/
							UNION

							SELECT
							'SUNNY VALLEY S.A.C.' AS TM_CCIADES,
							'0016' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0016CART
							Left Join RSFACCAR..CC0016LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0016BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0016VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0016FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0016ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							Where
							CD_CCODCLI='$codigo_cliente' And
							(CD_CESTADO<>'A')   AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')

							UNION

							SELECT
							'SUNNY II' AS TM_CCIADES,
							'0017' AS TM_CCIA,
							'01' AS TM_TIPO,
							CD_CCODART AS TM_CODART,
							CD_CPERIOD AS TM_CGLOSA,
							CD_CTIPDOC+CD_CNRODOC AS TM_BUSCA,
							CD_CTIPDOC AS TM_TIPDOC,
							CD_CLOCEMI AS TM_LOCEMI,
							CD_CNRODOC AS TM_NRODOC,
							CD_CORIGEN AS TM_ORIGEN,
							CD_CCODCLI AS TM_CODCLI,
							CD_CDEBHAB AS TM_DEBHAB,
							CD_NNROABO AS TM_NROABO,
							CD_DFECDOC AS TM_FECDOC,
							CD_CTDOREF AS TM_CTDREF,
							CD_CNROREF AS TM_NRODOCR,
							TM_CSERIE =CASE WHEN NOT B.F5_CNUMSER IS NULL THEN B.F5_CNUMSER WHEN NOT C.F5_CNUMSER IS NULL THEN C.F5_CNUMSER END,
							TM_CDOCVT =CASE WHEN NOT B.F5_CNUMDOC IS NULL THEN B.F5_CNUMDOC WHEN NOT C.F5_CNUMDOC IS NULL THEN C.F5_CNUMDOC END,
							TM_DIATRA=CASe When Datediff(DAY,CD_DFECDOC,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECDOC,Getdate())<0 then 0 When Datediff(DAY,CD_DFECDOC,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECDOC,Getdate()) End,
							CD_DFECVEN AS TM_FECVEN,
							CD_DFECCAN AS TM_FECCAN,
							TM_DIAPLZ=CASe When Datediff(DAY,CD_DFECVEN,Getdate()) is null Then 0 When Datediff(DAY,CD_DFECVEN,Getdate())<0 then 0 When Datediff(DAY,CD_DFECVEN,Getdate())>999 then 999 Else Datediff(DAY,CD_DFECVEN,Getdate()) End,
							CD_CTIPMON AS TM_TIPMON ,
							CD_NIMPTMN AS TM_IMPTMN,
							CD_NIMPTUS AS TM_IMPTUS,
							CD_NSALDMN AS TM_SALDMN,
							CD_NSALDUS AS TM_SALDUS,
							CD_NTIPCAM AS TM_TIPCAM,
							CD_CTIPPRO AS TM_TIPPRO,
							TM_IMPORTE=CASE CD_CTIPMON When 'MN' Then CD_NIMPTMN Else CD_NIMPTUS End,
							TM_SALDO=CASE CD_CTIPMON When 'MN' Then CD_NSALDMN Else CD_NSALDUS End,
							TM_CCODVEN=CASe When VE_CTIPVEN='F' Then CD_CCODVEN+'/'+VE_CCODLIN Else CD_CCODVEN End,
							ISNULL(LT_CSITUAC,'') AS TM_LETSIT,
							ISNULL(LT_CNUMCOB,'') AS TM_NUMCOB,
							ISNULL(BC_CDESBAN,'') AS TM_DESBAN,
							CD_CTDOREF AS TM_TIPDOCREF,
							CD_CNROREF AS TM_NUMDOCREF,
							CD_CESTADO AS TM_ESTADO
							From RSFACCAR..CC0017CART
							Left Join RSFACCAR..CC0017LETR On CD_CTIPDOC='LT' AND CD_CNRODOC=LT_CNROLET
							Left Join RSFACCAR..CC0017BANC On LT_CCODBAN=BC_CCODBAN
							LEFT Join RSFACCAR..FT0017VEND On CD_CCODVEN=VE_CCODIGO
							LEFT Join RSFACCAR..FT0017FACC AS B On CD_CTIPDOC=B.F5_CTD AND CD_CNRODOC=RTRIM(B.F5_CNUMSER)+RTRIM(B.F5_CNUMDOC) AND CD_CCODCLI=B.F5_CCODCLI
							LEFT Join RSFACCAR..FT0017ACUC AS C On CD_CTIPDOC=C.F5_CTD AND CD_CNRODOC=RTRIM(C.F5_CNUMSER)+RTRIM(C.F5_CNUMDOC) AND CD_CCODCLI=C.F5_CCODCLI
							Where
							CD_CCODCLI='$codigo_cliente' And
							(CD_CESTADO<>'A')   AND
							((LT_CSITUAC<>'GE' AND LT_CSITUAC<>'EM') OR ISNULL(LT_CSITUAC,'X')='X')


						) AS T
						WHERE
						T.TM_ESTADO='V' AND

						0<>	CASE LTRIM(RTRIM(TM_TIPMON))
							WHEN 'US' THEN TM_SALDUS
							WHEN 'MN' THEN TM_SALDMN
							ELSE 0 END -- NO MUESTRA LOS SALDO 0

						ORDER BY T.TM_CCIA,T.TM_CODCLI,T.TM_TIPDOC,T.TM_NRODOC

								";


		$pr = $connection->prepare($sql_Exist_deuda);
		if ($pr->execute()) {
			$arr_cli = $pr->fetchAll(PDO::FETCH_ASSOC);
			if (count($arr_cli) > 0) {
				echo json_encode(array("rst" => true, "msg" => "Cliente Con Deuda"));
			} else {
				echo json_encode(array("rst" => false, "msg" => "Cliente Sin Deuda"));
			}
		}
	}

	public function ifexist_liquidacion($payi, $payf, $crei, $cref, $ruc) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();



		$pagoini = isset($payi) ? $payi : NULL;
		$pagofin = isset($payf) ? $payi : NULL;
		$creaini = isset($crei) ? $payi : NULL;
		$creafin = isset($cref) ? $payi : NULL;
		$cod_cli = isset($ruc) ? $ruc : NULL;

		if ($payi != '') {
			$pagoini = $payi;
		} else {
			$pagoini = NULL;
		}
		if ($payf != '') {
			$pagofin = $payf;
		} else {
			$pagofin = NULL;
		}
		if ($crei != '') {
			$creaini = $crei;
		} else {
			$creaini = NULL;
		}
		if ($cref != '') {
			$creafin = $cref;
		} else {
			$creafin = NULL;
		}
		if ($ruc != '') {
			$cod_cli = $ruc;
		} else {
			$cod_cli = NULL;
		}

		//echo $pagoini.'---'.$pagofin.'---'.$creaini.'---'.$creafin.'---'.$cod_cli;

		$sql_Exist_deuda = " EXECUTE SP_PROCESO_LIQUIDACION '$pagoini','$pagofin','$creaini','$creafin','$cod_cli' ";

		//echo $sql_Exist_deuda;
		//exit();

		$pr = $connection->prepare($sql_Exist_deuda, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));

		if ($pr->execute()) {
			$arr_cli = $pr->fetchAll(PDO::FETCH_ASSOC);
			// if($arr_cli[0]['CONT']>0){
			// echo count($arr_cli);
			// exit();

			if (count($arr_cli) > 0) {
				echo json_encode(array("rst" => true, "msg" => "Hay Registros"));
			} else {
				echo json_encode(array("rst" => false, "msg" => "No Hay Registros"));
			}
		}
	}

	public function ifexist_concepto($mes, $anio) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql_Exist_concep = "SELECT COUNT(*) AS CONT FROM FN_CONCEPTO($mes,$anio)";


		$pr = $connection->prepare($sql_Exist_concep);
		if ($pr->execute()) {
			$arr_con = $pr->fetchAll(PDO::FETCH_ASSOC);
			if ($arr_con[0]['CONT'] > 0) {
				echo json_encode(array("rst" => true, "msg" => "Hay Registros"));
			} else {
				echo json_encode(array("rst" => false, "msg" => "No Hay Registros"));
			}
		}
	}

	public function ifexist_historico_documento($inicio, $fin, $empresa, $tipdoc) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$where = "";
		if ($empresa != "") {
			$where .= " AND COD='$empresa'";
		}

		if ($tipdoc != "") {
			$where .= " AND TD='$tipdoc'";
		}

		$sql = "SELECT COUNT(*) AS CONT FROM FN_HISTORICO_DEUDA('$inicio','$fin') WHERE 1=1 $where";

		// echo $sql;
		// exit();

		$pr = $connection->prepare($sql);
		if ($pr->execute()) {
			$arr_con = $pr->fetchAll(PDO::FETCH_ASSOC);
			if ($arr_con[0]['CONT'] > 0) {
				echo json_encode(array("rst" => true, "msg" => "Hay Registros"));
			} else {
				echo json_encode(array("rst" => false, "msg" => "No Hay Registros"));
			}
		}
	}

	public function ifexist_historico_documento_detalle($inicio, $fin, $empresa, $tipdoc, $codclie) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		// $where = "";
		// if ($empresa != "") {
		// 	$where .= " AND COD='$empresa'";
		// }
		//
		// if ($tipdoc != "") {
		// 	$where .= " AND TD='$tipdoc'";
		// }
		// $sql = "SELECT COUNT(*) AS CONT FROM FN_HISTORICO_DEUDA_DETALLE('$inicio','$fin') WHERE 1=1 $where";

		$empr0002 = "";
		$empr0003 = "";
		$empr0004 = "";
		$empr0016 = "";

		if($empresa == "0002" ){
		    $empr0002 = $empresa;
		}
		if($empresa == "0003" ){
		    $empr0003 = $empresa;
		}
		if($empresa == "0004" ){
		    $empr0004 = $empresa;
		}
		if($empresa == "0016" ){
		    $empr0016 = $empresa;
		}
		if($empresa == "" ){
		    $empr0002 = "0002";
		    $empr0003 = "0003";
		    $empr0004 = "0004";
		    $empr0016 = "0016";
		}

		$sql = " EXECUTE SP_HISTORICO_DEUDA_DETALLE
									'$inicio','$fin','$codclie','$tipdoc',
									'$empr0002',
									'$empr0003',
									'$empr0004',
									'$empr0016'
		          ";

		//echo $sql;
		//exit();

		$pr = $connection->prepare($sql, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));

		if ($pr->execute()) {
			$arr_cli = $pr->fetchAll(PDO::FETCH_ASSOC);
			if (count($arr_cli) > 0) {
				echo json_encode(array("rst" => true, "msg" => "Hay Registros"));
			} else {
				echo json_encode(array("rst" => false, "msg" => "No Hay Registros"));
			}
		}



	}

	public function ifexist_tipo_cambio($inicio, $fin) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql = "	SELECT
					COUNT(*) AS CONT
					FROM RSCONCAR..CTCAMB
					WHERE
					CONVERT(DATETIME, XDATE, 103) BETWEEN CONVERT(DATETIME,'$inicio',103) AND CONVERT(DATETIME,'$fin',103) AND
					XCODMON='US'
					";

		$pr = $connection->prepare($sql);
		if ($pr->execute()) {
			$arr_con = $pr->fetchAll(PDO::FETCH_ASSOC);
			if ($arr_con[0]['CONT'] > 0) {
				echo json_encode(array("rst" => true, "msg" => "Hay Registros"));
			} else {
				echo json_encode(array("rst" => false, "msg" => "No Hay Registros"));
			}
		}
	}

	public function consultar_cliente($codigo_cliente) {

		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql = "	SELECT
					RTRIM(LTRIM(T.CL_CCODCLI))+' - '+RTRIM(LTRIM(T.CL_CNOMCLI)) AS name
					FROM
					(
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0001TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))
						-- UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						-- UNION
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						-- UNION
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						-- UNION
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT9999CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
					)  T
					WHERE
					RTRIM(LTRIM(T.CL_CCODCLI)) LIKE '%$codigo_cliente%' OR RTRIM(LTRIM(T.CL_CNOMCLI)) LIKE '%$codigo_cliente%'
					";

		// echo $sql;
		// exit();

		$pr = $connection->prepare($sql);
		$pr->execute();
		$arr_datos = $pr->fetchAll(PDO::FETCH_ASSOC);
		// echo json_encode(array("rst"=>true ,"data"=>$arr_datos,"msg"=>"Si hay Datos"));

		echo json_encode($arr_datos);


		// if ($pr->execute()) {
		// 	$arr_datos=$pr->fetchAll(PDO::FETCH_ASSOC);
		// 	if(count($arr_datos)>0){
		// 		echo json_encode(array("rst"=>true ,"datos"=>$arr_datos,"msg"=>"Si hay Datos"));
		// 	}else{
		// 		echo json_encode(array("rst"=>false,"datos"=>$arr_datos,"msg"=>"No hay Datos"));
		// 	}
		// }
	}

	public function consultar_codigo_cliente($valor) {

		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql = "	SELECT
					RTRIM(LTRIM(T.CL_CCODCLI))+' - '+RTRIM(LTRIM(T.CL_CNOMCLI)) AS name
					FROM
					(
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0001TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))
						-- UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)) --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0001CLIE  INNER JOIN RSFACCAR..AL0002TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0002CLIE  INNER JOIN RSFACCAR..AL0003TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0003CLIE  INNER JOIN RSFACCAR..AL0004TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0004CLIE  INNER JOIN RSFACCAR..AL0005TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0005CLIE  INNER JOIN RSFACCAR..AL0006TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0006CLIE  INNER JOIN RSFACCAR..AL0007TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						-- UNION
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0007CLIE  INNER JOIN RSFACCAR..AL0008TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0008CLIE  INNER JOIN RSFACCAR..AL0009TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						-- UNION
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0009CLIE  INNER JOIN RSFACCAR..AL0015TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						UNION
						SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  --  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0015CLIE  INNER JOIN RSFACCAR..AL0016TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
						-- UNION
						-- SELECT CL_CCODCLI,CL_CNOMCLI FROM RSFACCAR..FT9999CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO))  WHERE NOT CL_CCODCLI IN (SELECT CL_CCODCLI FROM RSFACCAR..FT0016CLIE  INNER JOIN RSFACCAR..AL9999TABL ON TG_CCOD='15' AND LTRIM(RTRIM(TG_CCLAVE))=LTRIM(RTRIM(CL_CESTADO)))
					)  T
					WHERE
					RTRIM(LTRIM(T.CL_CCODCLI)) LIKE '%$valor%' OR RTRIM(LTRIM(T.CL_CNOMCLI)) LIKE '%$valor%'
					";

		// echo $sql;
		// exit();

		$pr = $connection->prepare($sql);
		$pr->execute();
		$arr_datos = $pr->fetchAll(PDO::FETCH_ASSOC);
		// echo json_encode(array("rst"=>true ,"data"=>$arr_datos,"msg"=>"Si hay Datos"));

		echo json_encode($arr_datos);


		// if ($pr->execute()) {
		// 	$arr_datos=$pr->fetchAll(PDO::FETCH_ASSOC);
		// 	if(count($arr_datos)>0){
		// 		echo json_encode(array("rst"=>true ,"datos"=>$arr_datos,"msg"=>"Si hay Datos"));
		// 	}else{
		// 		echo json_encode(array("rst"=>false,"datos"=>$arr_datos,"msg"=>"No hay Datos"));
		// 	}
		// }
	}

	public function consultar_base_cliente($codigo_cliente) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql = "	SELECT
        			-- [IDBASE_CLIENTE],
        			[RUC],
        			[CLIENTE],
        			[TIENDA_SUNNY],
        			[LOCALIDAD],
        			[ESTUDIO_EXTERNO],
        			[COD_ZONA],
        			[ZONA],
        			[COD_VEN],
        			[RESPONSABLE_ZONA],
        			[COD_VEN_RTC_JUNIOR],
        			[RTC],
        			[SUPERVISOR],
        			[TIPO_RIESGO],
        			[LINEA_BASE],
        			[SOBREGIRO_CAMPANIA],
        			[LINEA_CREDITO_TOTAL],
        			[TIPO_CLIENTE],
        			[DIRECCION],
        			[DISTRITO],
        			[PROVINCIA],
        			[DEPARTAMENTO],
        			[TELEFONO],
        			[REPRESENTANTE],
        			[CORREO]
        			FROM
        			BASE_CLIENTE
        			WHERE
        			RUC='$codigo_cliente'
        			";

		$pr = $connection->prepare($sql);

		if ($pr->execute()) {
			$arr = $pr->fetchAll(PDO::FETCH_ASSOC);
			if (count($arr) > 0) {
				echo json_encode(array("rst" => true, "msg" => "Hay Registros", "datos" => $arr));
			} else {
				echo json_encode(array("rst" => false, "msg" => "No Hay Registros", "datos" => $arr));
			}
		}
	}

	public function update_base_cliente($codigo_cliente, $idsuper, $idtip_ries, $idlin_ba, $idsobreg, $idlin_cre, $idtelf, $idemail, $idrepren, $idlocali, $iddirecc, $iddistri, $idprovin, $iddeparta, $idtienda, $idest_ext) {

		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$update = "	UPDATE BASE_CLIENTE SET
					SUPERVISOR='$idsuper',
					TIPO_RIESGO='$idtip_ries',
					LINEA_BASE='$idlin_ba',
					SOBREGIRO_CAMPANIA='$idsobreg',
					LINEA_CREDITO_TOTAL='$idlin_cre',
					TELEFONO='$idtelf',
					CORREO='$idemail',
					REPRESENTANTE='$idrepren',
					LOCALIDAD='$idlocali',
					DIRECCION='$iddirecc',
					DISTRITO='$iddistri',
					PROVINCIA='$idprovin',
					DEPARTAMENTO='$iddeparta',
					TIENDA_SUNNY='$idtienda',
					ESTUDIO_EXTERNO='$idest_ext'
					WHERE
					RUC='$codigo_cliente'
					";
		$pr = $connection->prepare($update);
		$pr->execute();

		echo json_encode(array("rst" => true, "msg" => "Se actualizo Cliente"));
	}

	public function consultar_linea_credito($codigo_cliente) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql = "SELECT LINEA_BASE,SOBREGIRO_CAMPANIA,LINEA_CREDITO_TOTAL,COD_ZONA,ZONA,COD_VEN_RTC_JUNIOR,RTC,SUPERVISOR,TIPO_RIESGO,OBS FROM BASE_CLIENTE WHERE RUC='$codigo_cliente'";
		$pr = $connection->prepare($sql);
		$pr->execute();
		$arr = $pr->fetchAll(PDO::FETCH_ASSOC);

		$linea_base = $arr[0]['LINEA_BASE'];
		$sobregiro = $arr[0]['SOBREGIRO_CAMPANIA'];
		$linea_credito_tot = $arr[0]['LINEA_CREDITO_TOTAL'];

		$cod_zona = $arr[0]['COD_ZONA'];
		$nom_zona = $arr[0]['ZONA'];
		$tip_riesgo = $arr[0]['TIPO_RIESGO'];

		$cod_vend = $arr[0]['COD_VEN_RTC_JUNIOR'];
		$nom_vend = $arr[0]['RTC'];

		$supervisor = $arr[0]['SUPERVISOR'];
		$obs = $arr[0]['OBS'];


		$infcred = "EXECUTE SP_GERENCIAL
					'0002','300,304,30401,305,30501,30502,30503,30521,30522,306,30601,3061,30611,307,30701,30702,30703,308,309,310,311,312,313,3131,314,31401,315,31501,316,317,318,319,31901,320,321,322,323,324,3132','$codigo_cliente','','','0001', '',
					'0003','300,304,30401,305,30501,30502,30503,30521,30522,306,30601,3061,30611,307,30701,30702,30703,308,309,310,311,312,313,3131,314,31401,315,31501,316,317,318,319,31901,320,321,322,323,324,3132','$codigo_cliente','','','0001',  '',
					'0004','300,304,30401,305,30501,30502,30503,30521,30522,306,30601,3061,30611,307,30701,30702,30703,308,309,310,311,312,313,3131,314,31401,315,31501,316,317,318,319,31901,320,321,322,323,324,3132','$codigo_cliente','','','0001',  '',
					'0016','300,301,3011,3012,3013,3014,3015,3016,3017,3018,302,3021,3022,3023,3024,303,3031,3032,304,30401,3041,305,30501,30502,30503,3051,3052,3053,306,30601,3061,307,30702,30703,308,309,310,312,3131,314,315,316,317,318,319,31901,320,321,324','$codigo_cliente','','','', '' ";

		$pr_infcred = $connection->prepare($infcred, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
		$pr_infcred->execute();

		$tot_sald_dol = 0;
		while ($datos_muestra = $pr_infcred->fetch(PDO::FETCH_ASSOC)) {
			$tot_sald_dol = $tot_sald_dol + $datos_muestra['SALDO_TOTAL_US'];
		}

		$saldo_consumido = $tot_sald_dol;

		$diferencia = $arr[0]['LINEA_BASE'] - $tot_sald_dol;

		$descrip = "";

		if ($diferencia > 0) {
			$descrip = "Disponible";
		} else if ($diferencia < 0 && $arr[0]['LINEA_BASE'] == 0) {
			$descrip = "Sobregirado sin Saldo";
		} else if ($diferencia < 0) {
			$descrip = "Sobregirado con Saldo";
		} else if ($diferencia == 0) {
			$descrip = "No Disponible";
		} else {
			$descrip = "";
		}



		$ar_info = array(
			"linea_base" => $linea_base,
			"por_campania" => $sobregiro,
			"total" => $linea_base + $sobregiro,
			"saldo_consumido" => $saldo_consumido,
			"diferencia" => $diferencia,
			"descripcion" => $descrip,
			"cod_zona" => $cod_zona,
			"nom_zona" => $nom_zona,
			"tipo_riesgo" => $tip_riesgo,
			"cod_vend" => $cod_vend,
			"nom_vend" => $nom_vend,
			"supervisor" => $supervisor,
			"obs" => $obs
		);

		echo json_encode(array("rst" => true, "msg" => "Se actualizo Cliente", "datos" => $ar_info));
	}

	public function consulta_vendedor_general($valor) {

		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql = "SELECT LTRIM(RTRIM(VE_CCODIGO))+' - '+LTRIM(RTRIM(VE_CNOMBRE)) AS name FROM FT0002VEND WHERE VE_CTIPVEN = 'V' AND LTRIM(RTRIM(VE_CCODIGO)) LIKE '%$valor%' OR LTRIM(RTRIM(VE_CNOMBRE)) LIKE '%$valor%' ";

		// echo $sql;
		// exit();

		$pr = $connection->prepare($sql);
		$pr->execute();
		$arr_datos = $pr->fetchAll(PDO::FETCH_ASSOC);

		echo json_encode($arr_datos);
	}

	public function consulta_zona_general($valor) {

		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$sql = "SELECT LTRIM(RTRIM(ZV_CCODZON))+' - '+LTRIM(RTRIM(ZV_CNOMZON)) AS name FROM FT0002ZONV WHERE LTRIM(RTRIM(ZV_CCODZON)) LIKE '%$valor%' OR LTRIM(RTRIM(ZV_CNOMZON)) LIKE '%$valor%' ";

		// echo $sql;
		// exit();

		$pr = $connection->prepare($sql);
		$pr->execute();
		$arr_datos = $pr->fetchAll(PDO::FETCH_ASSOC);

		echo json_encode($arr_datos);
	}

	public function ifexist_cartas($rtc, $zona) {
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$xrtc = empty($rtc) ? '' : $rtc;
		$xzona = empty($zona) ? '' : $zona;




		$sql = "	EXECUTE SP_GERENCIAL
					'0002','$xzona',NULL,NULL,NULL,'0001','$xrtc',
					'0003','$xzona',NULL,NULL,NULL,'0001','$xrtc',
					'0004','$xzona',NULL,NULL,NULL,'0001','$xrtc',
					'0016','$xzona',NULL,NULL,NULL,'0000','$xrtc'";
//		 echo $sql;
//		 exit();

		$pr = $connection->prepare($sql);
		if ($pr->execute()) {
			$arr_con = $pr->fetchAll(PDO::FETCH_ASSOC);
			if (count($arr_con) > 0) {
				echo json_encode(array("rst" => true, "msg" => "Hay Registros"));
			} else {
				echo json_encode(array("rst" => false, "msg" => "No Hay Registros"));
			}
		}
	}

	public function RefreshCantEmail(){
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$countMail = " SELECT COUNT(*) AS 'COUNT' FROM CORREO_ENVIO WHERE FECHA_ENVIO IS NULL ";
		$pCount = $connection->prepare($countMail);
		if ($pCount->execute()) {
			$arr_count = $pCount->fetchAll(PDO::FETCH_ASSOC);

			$sqlasunto = " SELECT CONVERT(NVARCHAR(MAX), FECHA_PROGRAMADO, 103) AS FECHA_PROGRAMADO,ESTADO FROM CORREO_ASUNTO WHERE IDCORREO_ASUNTO = 1 ";
			$prasunto = $connection->prepare($sqlasunto);
			if ($prasunto->execute()) {
				$arr_asunto = $prasunto->fetchAll(PDO::FETCH_ASSOC);

				echo json_encode(array('rst'=>true,'cant'=>$arr_count[0]['COUNT'], 'fecha_prog'=>$arr_asunto[0]['FECHA_PROGRAMADO'], 'estado'=>$arr_asunto[0]['ESTADO']   ));
			}



		}
	}

	public function CargarEmail(){
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$ExecLoadCorreo = "	SP_ACCOUNT_STATUS
							'0002'  ,
							'0003'  ,
							'0004'  ,
							'0005'  ,
							'0006'  ,
							'0007'  ,
							'0016'  ,
							'0017'  ,
							'' ,
							2";

		$pr = $connection->prepare($ExecLoadCorreo);
		if ($pr->execute()) {

			$countMail = " SELECT COUNT(*) AS 'COUNT' FROM CORREO_ENVIO WHERE FECHA_ENVIO IS NULL ";
			$pCount = $connection->prepare($countMail);
			if ($pCount->execute()) {
				$arr_count = $pCount->fetchAll(PDO::FETCH_ASSOC);

				echo json_encode(array('rst'=>true,'cant'=>$arr_count[0]['COUNT']));

			}


		}
	}

	public function Save_Programacion($idfecha_program,$idestadoprog){
		$factoryConnection = FactoryConnection::create('mssql');
		$connection = $factoryConnection->getConnection();

		$ExecLoadCorreo = " UPDATE CORREO_ASUNTO SET FECHA_PROGRAMADO= CONVERT(DATETIME, '$idfecha_program', 103)  ,ESTADO=$idestadoprog WHERE IDCORREO_ASUNTO = 1 ";

	//		echo $ExecLoadCorreo;
	//		exit();

		$pr = $connection->prepare($ExecLoadCorreo);
		if ($pr->execute()) {
			echo json_encode(array('rst'=>true,'rpta'=>'Se actualizo los datos'  ));
		}
	}

	}

	?>
